<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ccx.Api\Ccx.Api.csproj" />
    <ProjectReference Include="..\Ccx.Tools\Ccx.Tools.csproj" />
  </ItemGroup>

</Project>
